title: Default Page

tabs:
  content:
    columns:
      main:
        width: 3/3
        sections:
          fields:
            type: fields
            fields:
              blocks:
                extends: fields/block-field

      sidebar: false

      # sidebar:
      #   width: 1/3
      #   sections:
      #     pages:
      #       type: pages
      #       template: default
      #       max: 0
      #     files:
      #       type: files
      #       max: 0

  seo: seo/page
